### PR TITLE
feat: modifier byAttribute for dynamic attribute autofocuse

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by Scrum** [comment]
@Botre ping

**Comment by Botre** [comment]
Hello, 

Thank you for your pull request!
If you want to dynamically set the autofocus attribute  you can already do so natively (see snippet below), I don't understand the exact added value considering this.

Am I missing something here?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  </head>

  <body>
    <div id="app">
      <input type="text" />
      <input type="text" :autofocus="af" />
    </div>
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script>
      new Vue({
        el: "#app",
        data() {
          return {
            af: true
          };
        }
      });
    </script>
  </body>
</html>
```

**Comment by Scrum** [comment]
@Botre  Hi
> Am I missing something here?

you all say right, but I have a situation in which I need to clearly trigger a focus event like this)
`Blocked autofocusing on a form control in a cross-origin subframe`

**Comment by Botre** [comment]
Oh I see,

What do you think about the following implementation?
Instead of using the `autofocus` directive to control whether or not to trigger the event, it uses a directive argument instead.

```javascript
// Register a global custom directive called `v-focus`
const directive = {
  // When the bound element is inserted into the DOM...
  inserted: function(el, binding) {
    if (typeof binding.value !== "undefined" && !binding.value) {
      return;
    }
    el.focus();
  }
};

export default directive;
```

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Demo</title>
  </head>
  <body>
    <div id="app">
      <input v-autofocus="isDesktop" type="text" />
    </div>
    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="./dist/vue-autofocus-directive.js"></script>
    <script>
      Vue.directive("autofocus", window["vue-autofocus-directive"].default);
      new Vue({
        el: "#app",
        data() {
          return {
            isDesktop: true
          };
        }
      });
    </script>
  </body>
</html>
```

BR

**Comment by Scrum** [comment]
@Botre Yes, your decision is more elegant, but unfortunately it carries less information about actions, although it increases your imagination)

**Comment by Botre** [comment]
Merged into master, built & deployed to NPM as 1.0.2.

Thank you!

**Pull request merged**
